on:
  pull_request: null
  push:
    branches:
      - master

name: CI

jobs:
  Analysis:
    strategy:
      matrix:
        php-versions: ['8.5']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.3.0
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values: post_max_size=256M, log_errors=1
          coverage: none
          tools: pecl
          extensions: inotify

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Coding Guidelines
        run: composer test:lint

      - name: Static Analyzer (PHPStan)
        run: composer test:phpstan

  Tests:
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.3.0
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values: post_max_size=256M, log_errors=1
          coverage: xdebug
          tools: pecl
          extensions: inotify

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Unit Tests
        run: composer test:unit

      - name: Mutation Tests
        run: composer test:mutation

      - name: Export coverage to codecov
        uses: codecov/codecov-action@v1
